name: my workflow

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Resotre nuget packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build
      
      - name: Run unit tests
        run: dotnet test